### ISSUE TITLE
Runtime error caused by invalid parameter type when number converted to integer

### ISSUE THREAD

**Issue by MartinRixham** [MartinRixham/Yirgacheffe#1]
When a number is converted to and integer then passed to the println method it silently converted back to a double causing an error at runtime

```
import java.io.PrintStream;

class MyClass
{
    main method(Array<String> args)
    {
        PrintStream out = new System().getOut();

        out.println(1.intValue());
    }
}
```
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    MyClass.method(Lyirgacheffe/lang/Array;)V @20: invokevirtual
  Reason:
    Type double_2nd (current frame, stack[2]) is not assignable to integer
  Current Frame:
    bci: @20
    flags: { }
    locals: { 'MyClass', 'yirgacheffe/lang/Array', 'java/io/PrintStream' }
    stack: { 'java/io/PrintStream', double, double_2nd }
  Bytecode:
    0x0000000: bb00 0859 b700 0cb6 0010 4d2c 0fb8 0016
    0x0000010: b600 1a87 b600 20b1                    

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```
The bytecode includes an unwanted i2d at instruction 19:
```
         0: new           #8                  // class yirgacheffe/lang/System
         3: dup
         4: invokespecial #12                 // Method yirgacheffe/lang/System."<init>":()V
         7: invokevirtual #16                 // Method yirgacheffe/lang/System.getOut:()Ljava/io/PrintStream;
        10: astore_2
        11: aload_2
        12: dconst_1
        13: invokestatic  #22                 // Method java/lang/Double.valueOf:(D)Ljava/lang/Double;
        16: invokevirtual #26                 // Method java/lang/Double.intValue:()I
        19: i2d
        20: invokevirtual #32                 // Method java/io/PrintStream.println:(I)V
        23: return
```

**Comment by MartinRixham** [comment]
The correct behaviour is for the i2d conversion to happen then the value to be printed as a double.
