### ISSUE TITLE
Compile time error when compiling empty return statement

### ISSUE THREAD

**Issue by MartinRixham** [MartinRixham/Yirgacheffe#2]
Compiler cannot handle empty return statement.

```
class MyClass
{
    private Void method()
    {
        return;
    }
}
```
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at yirgacheffe.lang.Array.pop(Array.java:92)
	at yirgacheffe.compiler.listener.StatementListener.exitReturnStatement(StatementListener.java:92)
	at yirgacheffe.parser.YirgacheffeParser$ReturnStatementContext.exitRule(YirgacheffeParser.java:3308)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at yirgacheffe.compiler.Compiler.execute(Compiler.java:78)
	at yirgacheffe.compiler.Compiler.compile(Compiler.java:62)
	at yirgacheffe.compiler.Yirgacheffe.execute(Yirgacheffe.java:58)
	at yirgacheffe.compiler.Yirgacheffe.main(Yirgacheffe.java:18)
```

**Comment by MartinRixham** [comment]
Fix in commit e669a55379ea31b5a39e529821c016c934ff7c6f
