### ISSUE TITLE
Referencing field without this cuases compile time error.

### ISSUE THREAD

**Issue by MartinRixham** [MartinRixham/Yirgacheffe#3]
```
import java.io.PrintStream;

class MyClass
{
    PrintStream out = new System().getOut();

    main method(Array<String> args)
    {
        Num number = 1;

        out.println(number);
    }
}
```
The `out` should be `this.out`. If it is missing the compiler should emit an unknown local variable error.
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at yirgacheffe.lang.Array.get(Array.java:51)
	at yirgacheffe.compiler.expression.InvokeMethod.compile(InvokeMethod.java:100)
	at yirgacheffe.compiler.statement.FunctionCall.compile(FunctionCall.java:30)
	at yirgacheffe.compiler.statement.Block.compile(Block.java:48)
	at yirgacheffe.compiler.statement.Block.compile(Block.java:48)
	at yirgacheffe.compiler.listener.MethodListener.exitFunction(MethodListener.java:126)
	at yirgacheffe.parser.YirgacheffeParser$FunctionContext.exitRule(YirgacheffeParser.java:739)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at yirgacheffe.compiler.Compiler.execute(Compiler.java:78)
	at yirgacheffe.compiler.Compiler.compile(Compiler.java:62)
	at yirgacheffe.compiler.Yirgacheffe.execute(Yirgacheffe.java:58)
	at yirgacheffe.compiler.Yirgacheffe.main(Yirgacheffe.java:18)
```

**Comment by MartinRixham** [comment]
The problem was not really the lack of 'this' so much as the difficulty of type checking an unknown method.
